name: wordpress_client
description: A library written purely in dart to interact with Wordpress REST API in a fluent manner. Supports Authorization as well.
version: 6.1.9-pre
repository: https://github.com/ArunPrakashG/wordpress_client

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  temp_mail_gen: ^2.0.0
  path_provider: ^2.0.9

dependencies:
  cookie_jar: ^3.0.1
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  http_parser: ^4.0.0
  meta: ^1.7.0
  path: ^1.8.0
  synchronized: ^3.0.0
