name: wordpress_client
description: A library written purely in dart to interact with Wordpress REST
  API in a fluent manner. Supports Authorization as well.
version: 5.2.2
repository: https://github.com/ArunPrakashG/wordpress_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  temp_mail_gen: ^2.0.0
  test: ^1.14.4

dependencies:
  cookie_jar: ^3.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  http_parser: ^4.0.0
  path: ^1.8.0
