name: wordpress_client
description: A starting point for Dart libraries or applications.
version: 4.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  temp_mail_gen: ^1.0.0
  test: ^1.14.4

dependencies:
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0
  http_parser: ^4.0.0
  path: ^1.8.0
